apiVersion: v1
kind: Service
# default namespace
metadata:
  name: redis-img-service
spec:
  type: ClusterIP
  selector:
    # must match with deployment identifier
    app: redis-img
  ports:
    - name: redis
      protocol: TCP
      # external port
      port: 6379
      # internal port
      targetPort: 6379
---
apiVersion: v1
kind: Service
# default namespace
metadata:
  name: redis-stack-service
spec:
  type: LoadBalancer
  selector:
    # must match with deployment identifier
    app: redis-img
  ports:
    - name: redis-stack
      protocol: TCP
      port: 8001
      targetPort: 8001
