apiVersion: apps/v1
kind: Deployment
# create the namespace
metadata:
  name: master-p2p
spec:
  replicas: 5
  selector:
    matchLabels:
      app: master-p2p
  template:
    metadata:
      labels:
        app: master-p2p
    spec:
      containers:
        - name: app
          image: ncavasin/sdypp-tp2-1
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          env:
            - name: redis-url
              value: redis://redis-img-service.default.svc.cluster.local:6379