apiVersion: v1
kind: Service
# default namespace
metadata:
  name: master-p2p-service
spec:
  type: LoadBalancer
  selector:
    # must match with deployment identifier
    app: master-p2p
  ports:
    - protocol: TCP
      # external port
      port: 8080
      # internal port
      targetPort: 8080
