apiVersion: v1
kind: Service
metadata:
  name: centralized-sobel-server                  # Nombre del Service
spec:
  selector:
    app: centralized-sobel-server                 # Nombre del deployment a exponer
  ports:
    - protocol: TCP
      port: 80                          # Puerto que el service recibe peticiones
      targetPort: 4001                  # Puerto interno al cual el service envia las peticiones
  type: LoadBalancer
