apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tp2-3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tp2-3
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageUtilization: 50