apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tp2-3-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tp2-3-api
  minReplicas: 3
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 5