apiVersion: apps/v1
kind: Deployment
metadata:
  # Deployment name
  name: tp2-3
spec:
  selector:
    matchLabels:
      # Label que le pondra a cada uno de los pods
      app: tp2-3
  replicas: 1
  # Hace referencia a la data de los pods de este deployment
  template: 
    metadata:
      labels:
        app: tp2-3
    spec:
      # Especifica los containers que tendra cada pod
      containers:
        - name: tp2-3            # Nombre del container dentro de los pods
          image: manuseligmann/sdypp-tp2-3-array    # Nombre de la imagen
          ports:
            - containerPort: 4001             # expone el puerto
          resources:
            requests: # Recursos minimos reservados para el pod.
              memory: "100Mi"
              cpu: "250m"
            limits: # Limite maximo que el pod puede consumir. Si lo superá, k8s lo reinicia.
              memory: "1024Mi"
              cpu: "1000m"