apiVersion: apps/v1
kind: Deployment
metadata:
  # Deployment name
  name: rabbit
spec:
  selector:
    matchLabels:
      # Label que le pondra a cada uno de los pods
      app: rabbit
  replicas: 1
  # Hace referencia a la data de los pods de este deployment
  template: 
    metadata:
      labels:
        app: rabbit
    spec:
      # Especifica los containers que tendra cada pod
      containers:
        - name: redis            # Nombre del container dentro de los pods
          image: rabbitmq:3-management    # Nombre de la imagen
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"
          ports:
            - containerPort: 5672             # expone el puerto