apiVersion: v1
kind: Service
metadata:
  name: redis    # Nombre del Service
spec:
  selector:
    app: redis   # Nombre del deployment a exponer
  ports:
    - protocol: TCP
      port: 6379            # Puerto que el service expone al exterior.
      targetPort: 6379    # puerto interno de los pods
  type: ClusterIP