apiVersion: apps/v1
kind: Deployment
metadata:
  # Deployment name
  name: warehouse
spec:
  selector:
    matchLabels:
      # Label que le pondra a cada uno de los pods
      app: warehouse
  replicas: 1
  # Hace referencia a la data de los pods de este deployment
  template: 
    metadata:
      labels:
        app: warehouse
    spec:
      # Especifica los containers que tendra cada pod
      containers:
        - name: warehouse            # Nombre del container dentro de los pods
          image: manuseligmann/sdypp-tp2-4-b-warehouse    # Nombre de la imagen
          env:
            # Server
            - name: PORT
              value: "5001"
            # RabbitMQ config
            - name: RABBIT_PROTOCOL
              value: "amqp"
            - name: RABBIT_HOST
              value: "rabbit"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USERNAME
              value: "user"
            - name: RABBIT_PASSWORD
              value: "password"
            - name: RABBIT_REQUEST_QUEUE
              value: "messages-to-process"
            - name: RABBIT_RESPONSE_QUEUE
              value: "processed-messages"
            # Redis config
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_USERNAME
              value: ""
            - name: REDIS_PASSWORD
              value: ""
          ports:
            - containerPort: 5001             # expone el puerto