apiVersion: v1
kind: Service
# default namespace
metadata:
  name: redis-img-service
spec:
  type: ClusterIP
  selector:
    # must match with deployment identifier
    app: redis-img
  ports:
    - protocol: TCP
      # external port
      port: 6379
      # internal port
      targetPort: 6379
