apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-img
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 5
  selector:
    matchLabels:
      app: redis-img # identifier
  template:
    metadata:
      labels:
        app: redis-img # identifier
    spec:
      containers:
        - name: redis-img # container name
          image: redis
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "5Gi"
          ports:
            - containerPort: 6379
